#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    wordpress-ddev-composer-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^wordpress-ddev-composer\.ddev\.site$`)
      
      service: "wordpress-ddev-composer-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "wordpress-ddev-composer-redirectHttps"
    wordpress-ddev-composer-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^wordpress-ddev-composer\.ddev\.site$`)
      
      service: "wordpress-ddev-composer-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "wordpress-ddev-composer-redirectHttps"
    
    
    
    wordpress-ddev-composer-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^wordpress-ddev-composer\.ddev\.site$`)
      
      service: "wordpress-ddev-composer-web-80"
      ruleSyntax: v3
      
      tls: true
      
    wordpress-ddev-composer-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^wordpress-ddev-composer\.ddev\.site$`)
      
      service: "wordpress-ddev-composer-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    wordpress-ddev-composer-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    wordpress-ddev-composer-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-wordpress-ddev-composer-web:80
        
    wordpress-ddev-composer-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-wordpress-ddev-composer-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/wordpress-ddev-composer.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/wordpress-ddev-composer.key