name: ${COMPOSE_PROJECT_NAME}
  #ddev-generated
services:
  
  db:
    container_name: ddev-${DDEV_SITENAME}-db
    build:
      context: './.dbimageBuild'
      args:
        BASE_IMAGE: $DDEV_DBIMAGE
        username: 'luishuacho'
        uid: '1000'
        gid:  1000 
    image: ${DDEV_DBIMAGE}-${DDEV_SITENAME}-built
    cap_add:
      - SYS_NICE
    stop_grace_period: 60s
    working_dir: "/home/luishuacho"
    volumes:
      - type: "volume"
        source: "database"
        target: "/var/lib/mysql"
        volume:
          nocopy: true
       
      # On db container ddev_config is mounted rw so we can create snapshots
      - .:/mnt/ddev_config
      - ./db_snapshots:/mnt/snapshots
       
      - ddev-global-cache:/mnt/ddev-global-cache
    restart: "no"

    # The postgres image is set up for user 999, we won't try to change that.
    user:  '$DDEV_UID:$DDEV_GID' 
    hostname: wordpress-ddev-composer-db
    ports:
      - "127.0.0.1:$DDEV_HOST_DB_PORT:3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: wordpress
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - COLUMNS
      - BITNAMI_VOLUME_DIR=/bitnami/mysql
      - DDEV_DATABASE
      - DDEV_DATABASE_FAMILY
      - DDEV_GOARCH
      - DDEV_GOOS
      - DDEV_HOSTNAME
      - DDEV_PHP_VERSION
      - DDEV_PRIMARY_URL
      - DDEV_PROJECT
      - DDEV_PROJECT_TYPE
      - DDEV_ROUTER_HTTP_PORT
      - DDEV_ROUTER_HTTPS_PORT
      - DDEV_SITENAME
      - DDEV_TLD
      - DOCKER_IP=127.0.0.1
      - HOST_DOCKER_INTERNAL_IP=
      - IS_DDEV_PROJECT=true
      - LINES
      - MYSQL_HISTFILE=/mnt/ddev-global-cache/mysqlhistory/${DDEV_SITENAME}-db/mysql_history
      - PGDATABASE=db
      - PGHOST=127.0.0.1
      - PGPASSWORD=db
      - PGUSER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=db
      - PAGER=${DDEV_PAGER-less -SFX}
      - TZ=America/Lima
      - USER=luishuacho
    command: ${DDEV_DB_CONTAINER_COMMAND}
    healthcheck:
      interval: "1s"
      retries: 70
      start_period: "120s"
      start_interval: "1s"
      timeout: "70s"
   

  web:
    container_name: ddev-${DDEV_SITENAME}-web
    build:
      context: './.webimageBuild'
      args:
        BASE_IMAGE: $DDEV_WEBIMAGE
        username: 'luishuacho'
        uid: '1000'
        gid: '1000'
        DDEV_PHP_VERSION: ${DDEV_PHP_VERSION}
        DDEV_DATABASE: ${DDEV_DATABASE}
    image: ${DDEV_WEBIMAGE}-${DDEV_SITENAME}-built
    command: /pre-start.sh

    networks: ["default", "ddev_default"]
    cap_add:
      - SYS_PTRACE
    working_dir: "/var/www/html/"

    

    volumes:
      
      - type: bind
        source: ../
        target: /var/www/html
         
        consistency: cached
         
       
      
      - .:/mnt/ddev_config:ro
      - ./xhprof:/usr/local/bin/xhprof:rw
      - ddev-global-cache:/mnt/ddev-global-cache
      - ddev-ssh-agent_socket_dir:/home/.ssh-agent

    restart: "no"
    user: '$DDEV_UID:$DDEV_GID'
    hostname: wordpress-ddev-composer-web

    ports:
      - "127.0.0.1:$DDEV_HOST_HTTP_PORT:80"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
    
    environment:
    - COLUMNS
    - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
    - COREPACK_HOME=/mnt/ddev-global-cache/corepack
    - DOCROOT=${DDEV_DOCROOT}
    - DDEV_COMPOSER_ROOT
    - DDEV_DATABASE
    - DDEV_DOCROOT
    - DDEV_DATABASE_FAMILY
    - DDEV_GOARCH
    - DDEV_GOOS
    - DDEV_HOSTNAME
    - DDEV_MUTAGEN_ENABLED
    - DDEV_PHP_VERSION
    - DDEV_PRIMARY_URL
    - DDEV_PROJECT
    - DDEV_PROJECT_TYPE
    - DDEV_ROUTER_HTTP_PORT
    - DDEV_ROUTER_HTTPS_PORT
    - DDEV_SITENAME
    - DDEV_TLD
    - DDEV_FILES_DIR
    - DDEV_FILES_DIRS
    - DDEV_WEB_ENTRYPOINT=/mnt/ddev_config/web-entrypoint.d
    - DDEV_WEBSERVER_TYPE
    - DDEV_XDEBUG_ENABLED
    - DDEV_VERSION
    - DEPLOY_NAME=local
    
    - DRUSH_OPTIONS_URI=$DDEV_PRIMARY_URL
    
    - DOCKER_IP=127.0.0.1
    - HOST_DOCKER_INTERNAL_IP=
    # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
    # To expose a container port to a different host port, define the port as hostPort:containerPort
    - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILPIT_PORT}:8025
    # You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
    # To expose an HTTPS port, define the port as securePort:containerPort.
    - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILPIT_HTTPS_PORT}:8025
    - IS_DDEV_PROJECT=true
    - LINES
    - MYSQL_HISTFILE=/mnt/ddev-global-cache/mysqlhistory/${DDEV_SITENAME}-web/mysql_history
    - NODE_EXTRA_CA_CERTS=/mnt/ddev-global-cache/mkcert/rootCA.pem
    - npm_config_cache=/mnt/ddev-global-cache/npm
    - PAGER=${DDEV_PAGER-less -SFX}
    - PGDATABASE=db
    - PGHOST=db
    - PGPASSWORD=db
    - PGUSER=db
    - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.${DDEV_TLD}
    - SSH_AUTH_SOCK=/home/.ssh-agent/socket
    - TZ=America/Lima
    - USER=luishuacho
    - VIRTUAL_HOST=${DDEV_HOSTNAME}
    - START_SCRIPT_TIMEOUT=30
    - "WP_ENVIRONMENT_TYPE=local"
    - "WP_CONTENT_DIR=/var/www/html/wp-content"
    - "WP_CONTENT_URL=${DDEV_PRIMARY_URL}/wp-content"
    - "DB_NAME=${DB_NAME}"
    - "DB_USER=${DB_USER}"
    - "DB_PASSWORD=${DB_PASSWORD}"
    - "WP_ENV=${WP_ENV}"
    - "WP_HOME=${WP_HOME}"
    - "WP_SITEURL=${WP_SITEURL}"
    
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: wordpress
      com.ddev.approot: $DDEV_APPROOT

      
    extra_hosts:
      - "host.docker.internal:host-gateway"
      

      
    external_links:
      - "ddev-router:wordpress-ddev-composer.ddev.site"
      
      
    healthcheck:
      interval: "1s"
      retries: 70
      start_period: "120s"
      start_interval: "1s"
      timeout: "70s"

networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
    
    labels:
      com.ddev.platform: ddev

volumes:
  
  database:
    name: "wordpress-ddev-composer-mariadb"
    external: true
   

   

  
  ddev-ssh-agent_socket_dir:
    external: true
  
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  
  
  
